[package]
name = "test_htmx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
maud = { version = "0.26", features = ["axum"] }
tokio = { version = "1", features = ["full"] }
